# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true
includes:
  aptos: { taskfile: aptos/Taskfile.yml, dir: ./aptos }
  avax: { taskfile: avax/Taskfile.yml, dir: ./avax }
  bitcoin: { taskfile: bitcoin/Taskfile.yml, dir: ./bitcoin }
  cosmos: { taskfile: cosmos/Taskfile.yml, dir: ./cosmos }
  ethereum: { taskfile: ethereum/Taskfile.yml, dir: ./ethereum }
  filecoin: { taskfile: filecoin/Taskfile.yml, dir: ./filecoin }
  helium: { taskfile: helium/Taskfile.yml, dir: ./helium }
  polkadot: { taskfile: polkadot/Taskfile.yml, dir: ./polkadot }
  solana: { taskfile: solana/Taskfile.yml, dir: ./solana }
  sui: { taskfile: sui/Taskfile.yml, dir: ./sui }
  tezos: { taskfile: tezos/Taskfile.yml, dir: ./tezos }

vars:
  GIT_ROOT:
    sh: git rev-parse --show-toplevel

tasks:
  default:
    cmds:
      - task: aptos:default
      - task: avax:default
      - task: bitcoin:default
      - task: cosmos:default
      - task: ethereum:default
      - task: filecoin:default
      - task: helium:default
      - task: polkadot:default
      - task: solana:default
      - task: sui:default
      - task: tezos:default
