# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true

vars:
  GIT_ROOT:
    sh: git rev-parse --show-toplevel
  DIRS:
    sh: find . -maxdepth 1 -type d -not -name ".git" | grep -v "^\.$"

tasks:
  default:
    cmds:
      - for: { var: DIRS }
        task: test
        vars:
          DIR: "{{.ITEM}}"

  release:
    run: always
    cmds:
      - for: { var: DIRS }
        task: bump
        vars:
          DIR: "{{.ITEM}}"
      - git push origin --tags
      - git push

  test:
    internal: true
    requires:
      vars: [DIR]
    dir: "{{.DIR}}"
    cmds:
      - gum spin --spinner dot --title "[{{.DIR}}] Running go mod tidy" -- go mod tidy
      - gum spin --spinner dot --title "[{{.DIR}}] Running go tests" -- go test -v
      - gum log --level info "[{{.DIR}}] Tests succeeded"

  bump:
    prompt: Continue with version bump?
    internal: true
    requires:
      vars: [DIR]
    dir: "{{.DIR}}"
    cmds:
      - cz bump --increment PATCH --allow-no-commit --yes
