# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true
vars:
  MOD: git.sonr.io/pkg/coins/tezos
tasks:
  default:
    run: always
    cmds:
      - gum format "# {{.MOD}}"
      - task: tidy
      - task: test

  tidy:
    run: always
    cmds:
      - gum spin --spinner dot --title "Running go mod tidy" -- go mod tidy

  test:
    run: always
    cmds:
      - gum spin --spinner dot --title "Running go tests" -- go test -v
      - gum log --level info "Tests succeeded"

  bump:
    run: always
    cmds:
      - cz bump --increment PATCH --allow-no-commit --yes
