[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "solana/v$version"
version_files = [
    "go.mod:module git.sonr.io/pkg/coins/solana"
]
version_scheme = "semver"
version = "0.0.2"
update_changelog_on_bump = true
major_version_zero = true
changelog_file = "CHANGELOG.md"
